openapi: 3.0.0
info:
  title: Portfolio Data
  description: "This is the SQL server containing all use case data.\nYou can find\
    \ out more about my usecases at [ai-for-everyone.org](ai-for-everyone.org).\n\
    You can find out more about Swagger at\n[http://swagger.io](http://swagger.io)\
    \ or on\n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  termsOfService: http://swagger.io/terms/
  contact:
    email: andreas.ditte01@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://virtserver.swaggerhub.com/andreas.ditte/data_from_portfolio_homepage/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://andreasdit.github.io/building_an_api/
tags:
- name: sonntagsfrage
  description: Everything about the Sonntagsfrage use case
  externalDocs:
    description: Find out more
    url: https://ai-for-everyone.org/archives/51
- name: twitter_monitor
  description: Everything about the Twitter use case
  externalDocs:
    description: Find out more
    url: https://ai-for-everyone.org/archives/2134
paths:
  /sonntagsfrage/survey:
    get:
      tags:
      - sonntagsfrage
      summary: Returns all past survey data
      description: Returns a json object with all historical data from the Sonntagsfrage
        survey
      operationId: getSurvey
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
            application/xml:
              schema:
                $ref: '#/components/schemas/Survey'
      security:
      - api_key: []
  /sonntagsfrage/survey/{Partei}:
    get:
      tags:
      - sonntagsfrage
      summary: Returns survey results of certain party
      description: "For valid response use one of the following party names PDS, AfD,\
        \ Linke_PDS, REP_DVU, PIRATEN, SPD, FDP, Sonstige, CDU_CSU, LINKE, GRUENE"
      operationId: getSurveyByParty
      parameters:
      - name: Partei
        in: path
        description: Name of the party
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
            application/xml:
              schema:
                $ref: '#/components/schemas/Survey'
        "400":
          description: Invalid Party supplied
  /sonntagsfrage/predictions:
    get:
      tags:
      - sonntagsfrage
      summary: Returns all predictions
      description: Returns a json object with all predictions for the Sonntagsfrage
        survey for past and the next sundays
      operationId: getPreds
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Predictions'
            application/xml:
              schema:
                $ref: '#/components/schemas/Predictions'
  /sonntagsfrage/predictions/{Partei}:
    get:
      tags:
      - sonntagsfrage
      summary: Returns predictions of certain party
      description: "For valid response use one of the following party names PDS, AfD,\
        \ Linke_PDS, REP_DVU, PIRATEN, SPD, FDP, Sonstige, CDU_CSU, LINKE, GRUENE"
      operationId: getPredsByParty
      parameters:
      - name: Partei
        in: path
        description: Name of the party
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Survey'
            application/xml:
              schema:
                $ref: '#/components/schemas/Survey'
        "400":
          description: Invalid Party supplied
  /twitter_monitor/tweets_compressed:
    get:
      tags:
      - twitter_monitor
      summary: Returns metrics
      description: Returns a json object with all metrics computed from hourly compression
        of tweets
      operationId: getTweets_comp
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Twitter_monitor'
            application/xml:
              schema:
                $ref: '#/components/schemas/Twitter_monitor'
components:
  schemas:
    Survey:
      type: object
      properties:
        Datum:
          type: string
          format: date
        Results:
          type: number
          format: float
        Partei:
          type: string
        Befraget:
          type: string
        Zeitraum:
          type: string
        meta_insert_ts:
          type: string
          format: date-time
      xml:
        name: Survey
    Predictions:
      type: object
      properties:
        Datum:
          type: string
          format: date
        Estimator:
          type: string
        Predictions:
          type: number
          format: float
        Partei:
          type: string
      xml:
        name: Predictions
    Twitter_monitor:
      type: object
      properties:
        hashtag:
          type: string
        meta_ts_hours_str:
          type: string
          format: date-time
        nb_of_tweets:
          type: integer
          format: int64
        avg_polarity_de:
          type: integer
          format: float
        stdev_polarity_de:
          type: integer
          format: float
        max_polarity_de:
          type: integer
          format: float
        min_polarity_de:
          type: integer
          format: float
        avg_polarity_en:
          type: integer
          format: float
        stdev_polarity_en:
          type: integer
          format: float
        max_polarity_en:
          type: integer
          format: float
        min_polarity_en:
          type: integer
          format: float
        avg_subjectivity_de:
          type: integer
          format: float
        avg_subjectivity_en:
          type: integer
          format: float
        stdev_subjectivity_en:
          type: integer
          format: float
        max_subjectivity_en:
          type: integer
          format: float
        min_subjectivity_en:
          type: integer
          format: float
      xml:
        name: Twitter_monitor
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
  requestBodies:
    SurveyPartei:
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Survey'
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://petstore.swagger.io/oauth/dialog
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
